build: false
version: 1.0.{build}

branches:
    only:
        - win

install:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 14 2015 Win64" ..
    - dir
    - cmake --build . --config Release --target shim
    - git status
    - cd lib
    - dir /s
    - dumpbin.exe lib\Release\fec.lib

